spring.application.name=MINI_S3
server.port=8081

spring.datasource.url=jdbc:mysql://localhost:3306/mini_s3
spring.datasource.username=root
spring.datasource.password=shaunak123

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

jwt.secret=mini-s3-development-secret-key-change-this-in-production
jwt.expiration=86400000
